# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
- "2.7.9"
addons:
  postgresql: "9.4"
before_script:
- psql -c 'CREATE DATABASE tournament;' -U postgres
- python createdb.py
before_install:
- pip install psycopg2
script: python unittests.py -b -v