# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
- "2.7.9"
addons:
  postgresql: "9.4"
matrix:
  include:
  - python: "2.7.9"
    addons:
      postgresql: "9.3"
before_script:
- psql -c 'CREATE DATABASE tournament;' -U postgres
- python tcdbfunc.py
before_install:
- pip install psycopg2
- pip install PrettyTable
script:
- python tests/test_db.py
- python tests/tcdbfunc.py
- python tests/test_tournament.py